name: Update Version

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Debug Info
        run: |
          echo "Current directory: $(pwd)"
          echo "List of files:"
          ls -al
          echo "Yarn version:"
          yarn --version
          echo "Node version:"
          node --version
          echo "Package.json content:"
          cat package.json

      - name: Bump version
        id: bump_version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          yarn version --patch --no-git-tag-version
          NEW_VERSION=$(node -p -e "require('./package.json').version")
          git add package.json
          git commit -m "chore(release): ${NEW_VERSION}"
          git tag v${NEW_VERSION}
          echo "Bumped version to ${NEW_VERSION}"
          echo "::set-output name=version::${NEW_VERSION}"

      - name: Push changes
        run: |
          git push origin HEAD --tags

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.bump_version.outputs.version }}
          release_name: Release v${{ steps.bump_version.outputs.version }}
          body: |
            Changes in this release:
            ${{ steps.bump_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
